    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/diegoturcios/Documents/Personal/PetProject/pettracker/migrations/env.py", line 113, in <module>
    run_migrations_online()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/diegoturcios/Documents/Personal/PetProject/pettracker/migrations/env.py", line 107, in run_migrations_online
    context.run_migrations()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 8, in run_migrations
  File "/Users/diegoturcios/Documents/Personal/PetProject/pettracker/venv/lib/python3.13/site-packages/alembic/runtime/environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/diegoturcios/Documents/Personal/PetProject/pettracker/venv/lib/python3.13/site-packages/alembic/runtime/migration.py", line 623, in run_migrations
    step.migration_fn(**kw)
    ~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/diegoturcios/Documents/Personal/PetProject/pettracker/migrations/versions/c99be3158653_initial_migration_with_user_role_field.py", line 21, in upgrade
    with op.batch_alter_table('location', schema=None) as batch_op:
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py", line 148, in __exit__
    next(self.gen)
    ~~~~^^^^^^^^^^
  File "/Users/diegoturcios/Documents/Personal/PetProject/pettracker/venv/lib/python3.13/site-packages/alembic/operations/base.py", line 397, in batch_alter_table
    impl.flush()
    ~~~~~~~~~~^^
  File "/Users/diegoturcios/Documents/Personal/PetProject/pettracker/venv/lib/python3.13/site-packages/alembic/operations/batch.py", line 115, in flush
    fn(*arg, **kw)
    ~~^^^^^^^^^^^^
  File "/Users/diegoturcios/Documents/Personal/PetProject/pettracker/venv/lib/python3.13/site-packages/alembic/ddl/impl.py", line 382, in drop_column
    self._exec(base.DropColumn(table_name, column, schema=schema))
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/diegoturcios/Documents/Personal/PetProject/pettracker/venv/lib/python3.13/site-packages/alembic/ddl/impl.py", line 246, in _exec
    return conn.execute(construct, params)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/diegoturcios/Documents/Personal/PetProject/pettracker/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "/Users/diegoturcios/Documents/Personal/PetProject/pettracker/venv/lib/python3.13/site-packages/sqlalchemy/sql/ddl.py", line 187, in _execute_on_connection
    return connection._execute_ddl(
           ~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/diegoturcios/Documents/Personal/PetProject/pettracker/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1527, in _execute_ddl
    ret = self._execute_context(
        dialect,
    ...<4 lines>...
        compiled,
    )
  File "/Users/diegoturcios/Documents/Personal/PetProject/pettracker/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/diegoturcios/Documents/Personal/PetProject/pettracker/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/diegoturcios/Documents/Personal/PetProject/pettracker/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/diegoturcios/Documents/Personal/PetProject/pettracker/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/diegoturcios/Documents/Personal/PetProject/pettracker/venv/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "health_flags" of relation "location" does not exist

[SQL: ALTER TABLE location DROP COLUMN health_flags]
(Background on this error at: https://sqlalche.me/e/20/f405)
